name: debug_desktop_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  centrifuge: ^0.5.1
  cupertino_icons: ^0.1.3
  flutter_simple_dependency_injection: ^1.0.2+1
  fluro: ^1.6.3
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  path_provider: ^1.6.10
  provider: ^4.1.3
  rxdart: ^0.24.1
  intl: ^0.16.1
  # shared_preferences: ^0.5.7+3
  shimmer: ^1.1.1
  sqflite: ^1.3.1
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  mobx_codegen: ^1.0.0
  pedantic: 1.8.0+1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: false

  assets:
    - assets/locale/ru.json
    - assets/db/schema_init.sql