targets:
  $default:
    sources:
      include:
        - $package$
        - lib/$lib$
        - lib/di/**
        - lib/domain/**
        - lib/feature/**
        - lib/services/**
        - lib/tools/**
      exclude:
        - test/**