name: multi_debugger
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  built_collection: ^4.3.2
  built_redux: ^7.5.11
  built_value: ^7.1.0
  centrifuge: # ^0.5.1
    path: packages/centrifuge
  cupertino_icons: ^0.1.3
  # flutter_built_redux: ^0.6.0
  flutter_simple_dependency_injection: ^1.0.3
  go_flutter_utils:
    git:
      url: git://github.com/jWinterDay/go_flutter_utils.git
  hive: ^1.4.3
  json_diff:
    path: packages/json_diff
  logger_flutter: ^0.7.1
  path_provider: ^1.6.11
  path_provider_linux: ^0.0.1+2
  path_provider_macos: ^0.0.4+3
  provider: ^4.3.2
  rxdart: ^0.24.1
  intl: ^0.16.1
  tuple: ^1.0.3
  url_launcher: ^5.5.0
  url_launcher_linux: ^0.0.1+1
  url_launcher_macos: ^0.0.1+7
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build: 1.3.0
  build_config: 0.4.2
  build_runner: 1.10.2
  built_value_generator: 7.1.0    
  # hive_generator: ^0.7.1
  pedantic: 1.10.0-nullsafety

flutter:
  uses-material-design: true
  assets:
    - application_bundle/
  fonts:
    - family: LoggerIcons
      fonts:
        - asset: assets/icons/Logger.ttf