version: '3'

services:
  # http://localhost:8001/#/
  centrifugo:
    image: centrifugo/centrifugo:v2.5
    container_name: dev_centrifugo
    restart: always
    # depends_on:
    #   - redis
    ports:
      - 8001:8001
    volumes:
      - ./config/centrifugo:/centrifugo
    command: centrifugo --config=config.json --admin --admin_insecure # --engine=redis --redis_host=redis --redis_password=password 
