name: centrifugo_flutter_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  centrifuge: ^0.5.1
  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.11
  path_provider_fde:
    path: plugins/path_provider_fde
  rxdart: ^0.24.1
  shared_preferences: ^0.5.7+3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  pedantic: ^1.9.0

dependency_overrides:
  dartx: ^0.2.0

flutter:
  uses-material-design: true