/// Flutter icons Logger
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Logger
///      fonts:
///       - asset: fonts/Logger.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LoggerIcons {
  LoggerIcons._();

  static const String _kFontFam = 'LoggerIcons';

  static const IconData addNew_1x = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrowDown_1x = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData autoscroll_1x = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData blacklistActive_1x = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData blacklistNull_1x = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clearInput_1x = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData close_1x = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData connect_1x = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData disconnect_1x = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit_1x = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData favoriteActive_1x = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData favoriteNull_1x = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData loader_1x = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData repeat_1x = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData search_1x = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData trash_1x = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData whitelistActive_1x = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData whitelistNull_1x = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData divider_1x = IconData(0xe813, fontFamily: _kFontFam);
}
